name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install depends
      run: sudo apt-get update && sudo apt-get install -y attr debhelper devscripts fakeroot libssl-dev xxd
    - name: make
      run: make
    - name: make test
      run: make test
    - name: sudo make install
      run: sudo make install
    - name: make clean
      run: sudo make clean
    - name: make deb
      run: make deb
